blueprint:
  name: Open and Lock on Return Home for Multiple Persons and Doors with Optional Garage
  description: Optionally opens multiple garage doors and unlocks multiple doors when any selected person returns home, then locks/closes after a delay.
  domain: automation
  input:
    person_entities:
      name: Person Entities
      description: Entities for the persons this automation applies to.
      selector:
        entity:
          domain: person
          multiple: true
    garage_doors:
      name: Garage Door Entities (Optional)
      description: Entities for your garage doors. Select "No Garage Door" if not needed.
      default: "input_boolean.no_garage_door"
      selector:
        entity:
          domain: cover
          multiple: true
    doors:
      name: Door Entities
      description: Entities for your door locks.
      selector:
        entity:
          domain: lock
          multiple: true
    delay_time:
      name: Delay Time (in minutes)
      description: Time to wait before locking/closing doors.
      default: 5
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: "minutes"

trigger:
  platform: state
  entity_id: !input "person_entities"
  from: 'not_home'
  to: 'home'

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ 'input_boolean.no_garage_door' not in garage_doors }}"
        sequence:
          - service: cover.open_cover
            data:
              entity_id: !input "garage_doors"

  - service: lock.unlock
    data:
      entity_id: !input "doors"

  - delay:
      minutes: !input delay_time

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ 'input_boolean.no_garage_door' not in garage_doors }}"
        sequence:
          - service: cover.close_cover
            data:
              entity_id: !input "garage_doors"

  - service: lock.lock
    data:
      entity_id: !input "doors"
